services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: breweries_dw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/breweries_dw
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    command: standalone
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./air_flow/dags:/opt/airflow/dags
      - ./air_flow/src:/opt/airflow/src
      - ./air_flow/logs:/opt/airflow/logs
      - ./air_flow/files:/opt/airflow/files
      

