services:
  # --- Banco de Dados de Metadados ---
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: breweries_dw
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- Spark Master (Imagem Oficial) ---
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    # Comando para iniciar como Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080" # UI do Spark Master
      - "7077:7077" # Porta de conexão
    volumes:
      - ./air_flow:/opt/airflow

  # --- Spark Worker (Imagem Oficial) ---
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    # Comando para iniciar como Worker apontando para o Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./air_flow:/opt/airflow

  # --- Airflow ---
  airflow:
    build: .
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/breweries_dw
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      # Variáveis para conectar ao Spark
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      SPARK_HOME: /home/airflow/.local/lib/python3.9/site-packages/pyspark
    command: standalone
    depends_on:
      - postgres
      - spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./air_flow/dags:/opt/airflow/dags
      - ./air_flow/src:/opt/airflow/src
      - ./air_flow/logs:/opt/airflow/logs
      - ./air_flow/files:/opt/airflow/files